### PR TITLE
allow SS5

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Comment by purplespider** [comment]
Thanks! Getting round to updating all my modules for SS5.

**Comment by xini** [comment]
No worries. I'm having another go at mine atm... ;)

**Comment by xini** [comment]
Can you also tag this please?

**Comment by dizzystuff** [comment]
+1 for a tag, please! :)

**Comment by purplespider** [comment]
Sorry, done!

https://github.com/purplespider/silverstripe-asset-alt-text/tree/1.2.1

**Comment by dizzystuff** [comment]
Thank you! :)

**Pull request merged**
